import { Container, Header } from "@/components/shared";

import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Next Pizza | Корзина",
	description: "Generated by create next app",
};

export default function DashBoardLayout({ children }: { children: React.ReactNode }) {
	return (
		<main className="min-h-screen bg-[#F4F1EE]">
			<Header className="border-b border-gray-200" hasSearch={false} hasCart={false} />
			<Container>{children}</Container>
		</main>
	);
}
