import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function DashBoardLayout({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
}
